### ISSUE TITLE
Web hosting

### ISSUE THREAD

**Issue by DeveloperWOW64** [onein528/onein528#1]
@onein528 You cannot use Vercel for just a readme, as it is not a buildable file or a piece of code and it will fail. If you wanted to directly have a website with just a readme, you should use GH pages.

**Comment by onein528** [comment]
Ah on going. I want to copy codes from FHWebsite.

**Comment by DeveloperWOW64** [comment]
> Ah on going. I want to copy codes from FHWebsite.

ahh okay. Hope it looks nice! @onein528 Svelte is a very easy language to self-teach, as that's what I did when writing mine and FH's website. Svelte is just HTML++

**Comment by onein528** [comment]
Good! One of the most things that I want to learn.
